name: socfonyapis
description: Socfony Server/Client APIs.
version: 1.0.1
repository: https://github.com/socfony/socfonyapis.git
homepage: https://socfony.com

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  fixnum: ^1.0.0
  grpc: ^3.0.2
  protobuf: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
