name: socfonyapis
description: Socfony Server/Client APIs.
version: 1.0.0
repository: https://github.com/socfony/socfonyapis.git
homepage: https://socfony.com

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  grpc: ^3.0.2

dev_dependencies:
  lints: ^1.0.0
